FROM bfren/alpine-s6:alpine<%= ${ALPINE_MINOR} %>-<%= ${BASE_REVISION} %>

ARG BF_IMAGE
ARG BF_VERSION

EXPOSE 3310

ENV \
    # the number of times per day freshclam will run to update definitions
    CLAMAV_FRESH_PER_DAY=12

COPY ./overlay /
COPY ./<%= ${CLAMAV_MINOR} %>/overlay /

RUN bf-install
