FROM bcgdesign/alpine-s6:auto

EXPOSE 3310

ENV \
    # the number of times per day freshclam will run to update definitions
    CLAMAV_FRESH_PER_DAY=12

COPY ./overlay /
COPY ./CLAMAV_BUILD /tmp/VERSION

RUN bf-install
