#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Create configuration files.
#======================================================================================================================

bf-echo "Generating clamd config."
bf-esh ${BF_TEMPLATES}/clamd.conf.esh ${CLAMAV_CLAMD_CONF}
bf-done

bf-echo "Generating freshclam config."
bf-esh ${BF_TEMPLATES}/freshclam.conf.esh ${CLAMAV_FRESHCLAM_CONF}
bf-done
