#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

bf-env "CLAMAV_DATABASE" "/var/lib/clamav"
bf-env "CLAMAV_CLAMD_CONF" "/etc/clamav/clamd.conf"
bf-env "CLAMAV_FRESHCLAM_CONF" "/etc/clamav/freshclam.conf"
