#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Download the clamav database.
#======================================================================================================================

if [ ! -f /var/lib/clamav/main.cvd ]; then
    bcg-echo "Downloading ClamAV database..."
    freshclam
    bcg-done
fi
