#!/usr/bin/with-contenv sh

#======================================================================================================================
# Download the clamav database
#======================================================================================================================

if [ ! -f /var/lib/clamav/main.cvd ]; then
    _echo "Downloading ClamAV database..."
    freshclam
    _done
fi
