#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Create configuration files.
#======================================================================================================================

bcg-echo "Writing clamd config..."
esh -o ${CLAMAV_CLAMD_CONF} \
    ${TEMPLATES}/clamd.conf.esh
bcg-done

bcg-echo "Writing freshclam config..."
esh -o ${CLAMAV_FRESHCLAM_CONF} \
    ${TEMPLATES}/freshclam.conf.esh
bcg-done
