#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Configure freshclam
#   -d use daemon mode
#   -c check n times per day
#======================================================================================================================

_echo "Configuring ClamAV updater to run ${FRESHCLAM_PER_DAY} times per day..."
freshclam -d -c ${FRESHCLAM_PER_DAY}
_done
