#!/usr/bin/with-contenv sh

#======================================================================================================================
# Configure freshclam
#   -d = use daemon mode
#   -c = check n times per day
#======================================================================================================================

_echo "configuring clamav updater to run ${FRESHCLAM_PER_DAY} times per day..."
freshclam -d -c ${FRESHCLAM_PER_DAY}
_done
