#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Download the clamav database.
#======================================================================================================================

if [ ! -f ${CLAMAV_DATABASE}/main.cvd ]; then
    bf-echo "Downloading ClamAV database..."
    freshclam
    bf-done
fi
