#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Run clamav in daemon mode.
#
# Clamd flags
#   -c  use specified configuration file
#======================================================================================================================

bcg-echo "Starting ClamAV daemon"
clamd -c /etc/clamav/clamd.conf
