name: build-main

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/build-main.yml'
      - 'overlay/**'
      - 'VERSION'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read ClamAV revision - revision
        uses: bencgreen/read-file-action@v1
        with:
          path: ./CLAMAV_REVISION
        id: clamav_revision
      -
        name: Read ClamAV version - build
        uses: bencgreen/read-file-action@v1
        with:
          path: ./CLAMAV_BUILD
        id: clamav_build
      -
        name: Read image version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bcgdesign/clamav:latest
            bcgdesign/clamav:${{ steps.version.outputs.content }}
            bcgdesign/clamav:clamav-${{ steps.clamav_revision.outputs.content }}
            bcgdesign/clamav:clamav-${{ steps.clamav_revision.outputs.content }}-${{ steps.version.outputs.content }}
            bcgdesign/clamav:clamav-${{ steps.clamav_build.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
