name: publish-0_103

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-0_103:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      -
        name: Read ClamAV revision - revision
        uses: bfren/read-file@v1
        with:
          file: ./0.103/CLAMAV_REVISION
        id: clamav_revision
      -
        name: Read ClamAV version - build
        uses: bfren/read-file@v1
        with:
          file: ./0.103/CLAMAV_BUILD
        id: clamav_build
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION_MAJOR
        id: version_major
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./0.103/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/clamav:latest
            bfren/clamav:${{ steps.version_major.outputs.contents }}
            bfren/clamav:${{ steps.version_minor.outputs.contents }}
            bfren/clamav:${{ steps.version.outputs.contents }}
            bfren/clamav:clamav0.103
            bfren/clamav:clamav${{ steps.clamav_revision.outputs.contents }}
            bfren/clamav:clamav${{ steps.clamav_build.outputs.contents }}
            bfren/clamav:clamav0.103-${{ steps.version_major.outputs.contents }}
            bfren/clamav:clamav0.103-${{ steps.version_minor.outputs.contents }}
            bfren/clamav:clamav0.103-${{ steps.version.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
